import styled from "@emotion/styled";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Futurama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Image src="/futurama.png" alt="mainImage" />
        <Powerd>powerd by DAEPYEONG</Powerd>
      </Main>
    </div>
  );
}

const Main = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Image = styled.img`
  width: 600px;
  margin-top: 2em;
`

const Powerd = styled.p`
  margin-top: 5em;
`